/**
  You need to create an express HTTP server in Node.js which will handle the logic of a todo list app.
  - Don't use any database, just store all the data in an array to store the todo list data (in-memory)
  - Hard todo: Try to save responses in files, so that even if u exit the app and run it again, the data remains (similar to databases)

  Each todo has a title and a description. The title is a string and the description is a string.
  Each todo should also get an unique autogenerated id every time it is created
  The expected API endpoints are defined below,
  1.GET /todos - Retrieve all todo items
    Description: Returns a list of all todo items.
    Response: 200 OK with an array of todo items in JSON format.
    Example: GET http://localhost:3000/todos
    
  2.GET /todos/:id - Retrieve a specific todo item by ID
    Description: Returns a specific todo item identified by its ID.
    Response: 200 OK with the todo item in JSON format if found, or 404 Not Found if not found.
    Example: GET http://localhost:3000/todos/123
    
  3. POST /todos - Create a new todo item
    Description: Creates a new todo item.
    Request Body: JSON object representing the todo item.
    Response: 201 Created with the ID of the created todo item in JSON format. eg: {id: 1}
    Example: POST http://localhost:3000/todos
    Request Body: { "title": "Buy groceries", "completed": false, description: "I should buy groceries" }
    
  4. PUT /todos/:id - Update an existing todo item by ID
    Description: Updates an existing todo item identified by its ID.
    Request Body: JSON object representing the updated todo item.
    Response: 200 OK if the todo item was found and updated, or 404 Not Found if not found.
    Example: PUT http://localhost:3000/todos/123
    Request Body: { "title": "Buy groceries", "completed": true }
    
  5. DELETE /todos/:id - Delete a todo item by ID
    Description: Deletes a todo item identified by its ID.
    Response: 200 OK if the todo item was found and deleted, or 404 Not Found if not found.
    Example: DELETE http://localhost:3000/todos/123

    - For any other route not defined in the server return 404

  Testing the server - run `npm run test-todoServer` command in terminal
 */
const express = require('express');
const bodyParser = require('body-parser');

const app = express();
app.use(express.json());
app.use(bodyParser.json());
const todolist = [];

app.get('/todos', (req, resp) => {
  const todos = todolist.map((todo) => {
    return { title: todo.title, description: todo.description };
  })
  resp.status(200).json(todos);

})

app.get('/todos/:id', (req, resp) => {
  let todoFound = false;
  todolist.forEach((todo) => {
    if (todo.id === req.params.id) {
      todoFound = true;
      resp.status(200).json({ todo });
    }
  })
  if (!todoFound) {
    resp.status(404).json({ error: '404 Not Found' });
  }
})

app.post('/todos', (req, resp) => {
  const todo = req.body;
  const uniqueId = Math.random().toString(36).substring(2, 9);
  const newtodo = {
    id: uniqueId,
    title: todo.title,
    description: todo.description
  }
  // console.log(newtodo);
  todolist.push(newtodo);
  resp.status(201).json({ newtodo });
  // resp.send(newtodo)
})

app.put('/todos/:id', (req, resp) => {
  let todoFound = false;
  const id = req.params.id;
  todolist.forEach((item) => {
    if (id === item.id) {
      todoFound = true;
      item.description = req.body.description;
      resp.status(200).json({ item });
    }
  })
  if (!todoFound) {
    resp.status(404).json('404 Not Found');
  }
})
app.delete('/todos/:id', (req, resp) => {
  const todoId = req.params.id;
  const todoIndex = todolist.findIndex(todo => todo.id === todoId);

  if (todoIndex === -1) {
    resp.status(404).json({ error: 'Todo not found' });
  } else {
    todolist.splice(todoIndex, 1);
    resp.status(200).json({ message: 'Todo deleted successfully' });
  }
})

app.listen(3001);

module.exports = app;